### ISSUE TITLE
hmmmm

### ISSUE THREAD

**Issue by TheCodingPsn** [ArtyomArtamonov/wallpaper-engine-downloader#4]
![image](https://github.com/ArtyomArtamonov/wallpaper-engine-downloader/assets/78592389/bf6289c8-810e-4891-92b2-c97aece48f37)

tsk tsk tsk

**Comment by ArtyomArtamonov** [comment]
If you think the binary was exposed to virus, you can build it from the source code yourself. That is one of the best features of open source!
